export interface Project {
  slug: string;
  title: string;
  role: string;
  techStack: string[];
  description: string[];
  gallery: string[];
}

export const projects: Project[] = [
  {
    slug: "geni",
    title: "Geni",
    role: "Founder / CEO",
    techStack: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Google Cloud", "Docker", "Next.js", "Tailwind CSS", "Prisma", "Stripe", "Redis", "MongoDB"],
    description: [
      "**The Problem:** Every year, elementary schools waste tens of thousands of dollars on generic edtech supplements. Imagine a fourth grader logging into her computer to do an assignment, she read \"John has 3 boxes of 6 cantaloupes\", and stare blankly. She\'s never seen a box of cantaloupes. She guesses, gets it wrong, doesn't know why, and quits out of frustration. The teacher must push her to finish, then dig through worksheets and dashboards trying to decide what to reteach.",
      "**The Solution:** Geni allows teachers to instantly generate digital math assignments with images, text, and audio tailored to each student’s specific interests and cultural background. This makes the assignment more engaging and relatable for every student. The platform provides real-time insights on student struggles and pedagogical tips for teacher intervention.",
      "**The Traction:** After sending hundereds of emails to schools with no responses, I cold-knocked on over 200 schools, despite 188 of them slamming the door, sometimes literally, in my face, Geni signed 12 paying schools and grew our userbase from 0 to 1,000+ MAU in just 60 days.",
      "**The Tech:** I designed our full-stack platform using Next.js, TypeScript, and Docker.  Our backend is built around a pipeline that orchestrates seven different Text, Image, and Audio models (three of which were fine-tuned by us and 1 developed from scratch). This is supported by Redis for caching and PostgreSQL/Prisma for data management. We have deployed our platform both on AWS or GCP depending on which service gave us free credits"
    ],
    gallery: [
      "/images/geni1.jpeg",
      "/images/geni2.png",
      "/images/geni3.png",
      "/images/geni4.png",
      "/images/geni5.png"
    ]
  },
  {
    slug: "research",
    title: "University of Illinois Nuclear Reactor",
    role: "Research Engineer",
    techStack: ["Python", "C++", "PyTorch", "Docker", "MOOSE",],
    description: [
      "**The Problem:** Many operators of nuclear reactors are not trained in reactor physics, some only have a high school diploma / GED, and as such, they are unable to make informed decisions about certain data-driven areas of reactor operations. This presents a major issue during safety-critical operations.",
      "**The Solution:** A natural language interface powered by an LLM that allows operators to easily query and understand the state of reactor components. This system interprets complex data generated by a custom simulation of the Illinois Micro Modular Reactor (built on export-controlled specifications using the MOOSE framework).",
      "**The Traction:** The system was presented to Idaho National Laboratory, and the Illinois Micro-Nuclear Reactor team, where it was validated and implemented as a proof of concept.",
      "**The Tech:** I created the simulation system using MOOSE, a physics-based simulation framework written in C++. We used a local LLM, finetuned LLAMA 2 70B, and a local Vector Database to store important data the LLM needed to know about our specific nuclear reactor.",
    ],
    gallery: [
      "/images/research1.png",
      "/images/research2.png",
      "/images/research3.png",
    ]
  }
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}
